###############################################################################
## PROJECT PARAMETERS                                                        ##
###############################################################################

# Overwrite parameters for a specific trial/participant.

[project]
participant_height = 1.72 # m # float if single person, list of float if multi-person (same order as the Static trials) # Only used for marker augmentation
participant_mass = 70.0 # kg # Only used for marker augmentation and scaling